### Package Imports

In [1]:
import numpy as np

# Array Basics

## List != Array

Le liste sono oggetti in python che possono contenere qualsiasi tipo di dato, mentre un array è sempre un oggetto che rappresenta una sequenza di elementi omogenei per tipo e di dimensioni predefinite.

In [2]:
my_list1 = [x * 10 for x in range(1, 11)]

my_list1

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

## Dalla lista creo l'array
Sintassi:

    my_list = ["a", "e", "i", "o", "u"]
    my_array = np.array(my_list)

## **TO DO**:

crea una lista che contiene i numeri della tabellina del 3 e poi trasformala in un array.

*N.B.*: Usa la list comprehensions per creare la lista di python, è una sintassi più compatta e piace di più anche all'interprete!

    lista_nuova = [ `operazione da fare per ogni elemento` for `elemento del ciclo` in range(`start`, `stop`, `step`)]

In [3]:
# crea la lista 
tab_tre = [x for x in range(0, 31, 3)]

#trasforma in array
array_tre = np.array(tab_tre, 'H')
array_tre

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30], dtype=uint16)

In [4]:
[x for x in range(0, 31, 3) if x%2 ==0]

[0, 6, 12, 18, 24, 30]

### Cosa Cambia

Differenza fondamentale tra Liste e Array di numpy è il tipo di dato che li popola.
- la lista contiene qualsiasi tipo di dato senza controllare che ci sia omogeneità tra i vari elementi
- l'array contiene un solo tipo di dato


In [5]:
lista_valida = [2, "hello", "world", 42]

# np.array(lista_valida)

## Un Limite o Una Feature? 

Il fatto che l'array si compoti in questo modo può sembrare un problema ma il fatto è che python cerca sempre di rendere la vita facile al programmatore e questo penalizza le prestazioni e rende difficile (alla macchina) l'esecuzione di particolari tipi di operazioni.

Dobbiamo pensare l'array come una sequenza di elementi tutti uguali messi in fila uno dopo l'altro, mentre la lista è un accozzaglia di elementi sparsi in giro di cui ne possiamo avere alcuni molto grandi altri molto piccoli e possiamo trovarli solo perchè ogni elemento ci dice dove sta il successivo, diventa quasi una caccia al tesoro!

<img src="arrayVSlists.jpg">

In [6]:
np.array(["a", "e", "i", "o", "u"])

array(['a', 'e', 'i', 'o', 'u'], dtype='<U1')

## Operazioni 

Altra grande differenza, gli array li posso considerare come un blocco di numeri e utilizzarli per operazioni matematiche

## **TO DO**:
Moltiplichiamo tutti i valori della **lista ** tabellina del 3 per il numero 4, *per farlo su una lista servirà un ciclo* 

In [15]:
tab_tre_per_quattro = []


168

Ora proviamo con l'array:


In [14]:
# arr_tre_per_quattro = ...

134

## Numeri si ma che tipo?

I tipi di dato sono principalmente tipi pensati per gestire e manipolare numeri più o meno grandi
La Documentazione di NumPy ci può aiutare a capire meglio quali sono i tipi di dato e come utilizzarli:
 - [Data Types](https://numpy.org/doc/stable/user/basics.types.html)

il fatto di avere tutti dati dello stesso tipo permette di poter gestire meglio la memoria e porta a notevoli vantaggi prestazionali sopratutto per grandi moli di dati


In [9]:
my_array1 = np.array(my_list1)
my_array1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [27]:
my_list2 = ["helloW", "world", "a", "b"]


In [29]:
my_array2 = np.array(my_list2)
my_array2

array(['helloW', 'world', 'a', 'b'], dtype='<U6')

## [Broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html)

L'operazione fatta prima per moltiplicare un array per un numero intero, può essere generalizzata. Possiamo, infatti, vedere il numero intero come un array monodimensionale.

Questo ci porta a concludere che per fare operazioni sugli array non devono per forza avere la stessa dimensione e forma.

In [32]:
a = np.array([[0.0, 10.0, 20.0, 30.0], [40.0, 50.0, 60.0, 70.0]])
b = np.array([1.,2.,3.])
# a + b 
a.shape

(2, 4)

devono però rispettare alcuni vincoli sulla forma ovvero la **shape**

## shape

L'attributo shape viene utilizzato per restituire le dimensioni di un array. L'attributo shape restituisce una tupla che rappresenta il numero di elementi presenti lungo ciascuna dimensione dell'array.
Quindi il primo numero rappresenta le righe, il secondo le colonne.

Per poter fare operazioni tra 2 array è necessario che il numero di colonne del primo sia uguale al numero di righe del secondo oppure che abbiano la stessa shape


In [35]:
c = np.array([0., 0.])
c.shape
b.shape
# a + c 
d = np.array([3.,4.,5.,6.])
d.shape


(1, 4)

## La forma può cambiare 

Il metodo reshape() in NumPy viene utilizzato per cambiare la forma di un array senza modificare i suoi dati. Consente di ridimensionare l'array in modo da adattarsi a una nuova forma specificata, purché il numero totale di elementi rimanga invariato.


Trasformare l'array: `[ 0  1  2  3  4  5  6  7  8  9 10 11]` in un array con 3 righe e 4 colonne


In [6]:
# la shape finale deve essere (3,4)
mio_array = np.array([ 0 , 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
mio_array.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Trasposizione

A volte è necessario rovesciare gli array facendo diventare riga ciò che era colonna.

Questa operazione è la trasposizione. 

In [44]:
# proviamo la trasposizione sull'array appena riformato


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

Quindi nella trasposizione cambia la shape e anche l'ordine dei dati!

### 

In [49]:


# Creiamo alcuni array con diverse dimensioni
array1D = np.array([1, 2, 3, 4, 5])  # Array unidimensionale
array2D = np.array([[1, 2, 3], [4, 5, 6]])  # Array bidimensionale
array3D = np.array([[

    [
        [1, 2], 
        [3, 4]
    ], 
    [
        [5, 6], 
        [7, 8]
    ], 
    [
        [9, 10],
        [11, 12]
    ]]])  # Array tridimensionale
array4D = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])
array3D.ndim

3

In [25]:
my_array1.dtype

dtype('int64')

In [30]:
my_array2.dtype

dtype('<U6')

## Creazione Array
Per il momento abbiamo creato noi gli array, con numpy ci sono dei metodi per creare array in modo più diretto.

### arange()
Per creare un array in NumPy utilizzando la funzione arange(), puoi specificare un intervallo di valori e un passo (incremento) tra i valori. La sintassi di base è la seguente:

Creazione di un array con arange:

`array = np.arange(start, stop, step)`

Dove:

- start: il valore di partenza dell'intervallo (incluso).
- stop: il valore finale dell'intervallo (escluso).
- step: il passo tra i valori.

Se non si specifica start, il valore predefinito è 0. Se non si specifica step, il valore predefinito è 1.



In [ ]:
# Crea un array di valori da 0 a 9

# Crea un array di valori da 5 a 14

# Crea un array di valori pari da 0 a 10

# Crea un array di valori da 10 a 1 (in ordine decrescente)


In [50]:
# Crea un array dei multipli di 10 tra le prime 9 cifre (escluso lo zero) e disponi l'array su 5 righe e 2 colonne
my_array = (np.arange(1, 11) * 10).reshape(5, 2)
my_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

### Valori in un intervallo

`linspace()` viene utilizzata per creare un array di valori equidistanti all'interno di un intervallo specificato. La sintassi di base di linspace() è la seguente:

`array = np.linspace(start, stop, num)`

Dove:

- start: il valore di partenza dell'intervallo.
- stop: il valore finale dell'intervallo.
- num: il numero di campioni da generare tra start e stop. Questo valore indica quanti elementi avrà l'array.

La differenza principale tra arange() e linspace() è che arange() utilizza un passo specifico tra i valori, mentre linspace() determina automaticamente il passo in base al numero di campioni richiesti.



In [ ]:
# crea array di 5 valori equidistanti da 0 a 10

# crea un array di 10 valori equidistanti da 0 a 1

# crea un array di 20 valori equidistanti da -1 a 1



In [53]:
import matplotlib.pyplot as plt
# linspace viene spesso usato in matplotlib per creare gli assi dei grafici. 
# facciamo un plot della fz sin(x)

# Genera valori x equidistanti utilizzando linspace
x = np # 100 valori equidistanti da 0 a 10

# Calcoliamo i corrispondenti valori y
y = np.sin(x)

# Tracciamo il grafico
plt.plot(x, y)
plt.title('Funzione Seno')
plt.xlabel('x')
plt.ylabel('sin(x)')
plt.grid(True)
plt.show()
#

TypeError: sin() takes from 1 to 2 positional arguments but 0 were given

### Numeri Casuali

La funzione numpy.random.rand() serve per generare valori casuali distribuiti uniformemente tra 0 e 1. 

Puoi specificare le dimensioni dell'array che desideri generare passando gli argomenti alla funzione. Ecco un esempio:

In [56]:
# Creazione di un array di numeri casuali con una dimensione specifica
array_casuali = np.random.rand(5)  # Array di 5 numeri casuali
print("Array di numeri casuali:")
print(array_casuali)

Array di numeri casuali:
[0.61173302 0.53735177 0.365448   0.16687376 0.84024733]


Per generare numeri casuali interi puoi utilizzare la funzione `numpy.random.randint()`. Questa funzione genera numeri interi casuali in un intervallo specificato.

Esempio:

In [57]:
array_casuali = np.random.randint(1, 11, size=5)  # Genera 5 numeri casuali nell'intervallo da 1 a 10
print("Array di numeri casuali da 1 a 10:")
print(array_casuali)

Array di numeri casuali da 1 a 10:
[ 5  6 10  6  4]


In [61]:
# genera array casuale di interi tra 1 a 100 per 1000 valori, quindi trasformarla in matrice a 3 dimensioni
rand_3d = ''

# Array slicing

è un modo potente per estrarre porzioni di array in base a determinati criteri. Con il slicing, puoi selezionare un sottoinsieme di elementi di un array in base alla loro posizione lungo uno o più assi.

Lo slicing degli array NumPy avviene specificando una sequenza di indici o intervalli separati da virgole all'interno delle parentesi quadre. Gli indici o gli intervalli indicano quali elementi dell'array verranno inclusi nella selezione.
- array[1:4] seleziona gli elementi dall'indice 1 all'indice 3 (l'indice finale è escluso).
- array[::2] seleziona ogni secondo elemento dell'array.
- matrice[:, 0] seleziona tutti gli elementi della prima colonna della matrice.
- matrice[1:, :2] seleziona una porzione rettangolare della matrice, includendo tutte le righe dalla seconda in poi e solo le prime due colonne.

In [ ]:
# usando l'array rand_3d seleziona le prime 2 righe di ogni colonna

In [62]:
# Slicing per selezionare una sezione di dimensioni 3x3x3 dalla matrice

In [63]:
# Slicing per selezionare la prima riga di ogni matrice nella dimensione 2

# Filtrare array

Sugli array è possibile fare operazioni booleane

In [64]:
# Array con i nomi dei prodotti
nomi_prodotti = np.array(["Prodotto 1", "Prodotto 2", "Prodotto 3", "Prodotto 4", "Prodotto 5"])

# Array con i prezzi dei prodotti
prezzi_prodotti = np.array([10.99, 19.99, 5.49, 7.95, 12.50])

# Stampiamo i due array
print("Nomi dei prodotti:", nomi_prodotti)
print("Prezzi dei prodotti:", prezzi_prodotti)

Nomi dei prodotti: ['Prodotto 1' 'Prodotto 2' 'Prodotto 3' 'Prodotto 4' 'Prodotto 5']
Prezzi dei prodotti: [10.99 19.99  5.49  7.95 12.5 ]


In [66]:
cond_min10 = prezzi_prodotti <= 10

applicando l'array booleano a un array con i dati otterrò l'array filtrato

In [67]:
prezzi_prodotti[cond_min10]

array([5.49, 7.95])

In [38]:
# trovare nell'array rand_3d i tutti i valori > 90

array(['rare tomato', 'cola', 'gourmet ice cream'], dtype='<U17')

# Ordinamento

In [49]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])
prices.sort()

In [50]:
prices

array([ 4.99,  5.99,  6.99, 22.49, 49.99, 99.99])

In [51]:
# estrapolare i 3 prezzi più alti

array([22.49, 49.99, 99.99])

età dei dipendenti: 28 42 35 56 30 45 38 50 33 29 41 47 31 36 55 40 48 34 43 52 27 44 37 49 32 39 51 46 53 54

Creare un 

In [52]:
eta = np.zeros(30)
print(f"Mean: {eta.mean()}")
print(f"Min: {eta.min()}")
print(f"Max: {eta.max()}")
print(f"Median: {np.median(eta)}")

Mean: 57.49
Min: 22.49
Max: 99.99
Median: 49.99


#### Esempio dei larici 

Larice1
Larice2
Larice3
Larice4
Larice5
Larice6
Larice7
Larice8
Larice9
Larice10
Larice11
Larice12
Larice13
Larice14
Larice15


In [71]:
esposizione = np.array(
[
    "Sud",
    "Est",
    "Ovest",
    "Sud",
    "Est",
    "Est",
    "Ovest",
    "Est",
    "Est",
    "Nord",
    "Ovest",
    "Nord",
    "Nord",
    "Ovest",
    "Nord"
])
altezza = np.array(
[
    12,
    14,
    16,
    11,
    15,
    17,
    16,
    15,
    16,
    14,
    15,
    13,
    14,
    12,
    14,
])

# frequenza per le 4 esposizioni 



array([['Sud', 'Est', 'Ovest', 'Sud', 'Est', 'Est', 'Ovest', 'Est',
        'Est', 'Nord', 'Ovest', 'Nord', 'Nord', 'Ovest', 'Nord'],
       ['12', '14', '16', '11', '15', '17', '16', '15', '16', '14', '15',
        '13', '14', '12', '14']], dtype='<U21')